name: TestingApp
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  getauthtoken:
    runs-on: ubuntu-latest
    outputs:
      auth_token: ${{ steps.generate_token.outputs.token }}
    steps:
      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.REPO_AUTHENTICATOR_APP_ID }}

          # Optional.
          # github_api_url: https://api.example.com

          # Optional.
          # installation_id: 1337

          # Optional.
          # Using a YAML multiline string to avoid escaping the JSON quotes.
          # permissions: >-
          #   {"members": "read"}

          private_key: ${{ secrets.REPO_AUTHENTICATOR_APP_PRIVATE_KEY }}

          # Optional.
          # repository: owner/repo

      - name: Use token
        env:
          AUTH_TOKEN: ${{ steps.generate_token.outputs.token }}
        run: |
          echo "The generated token is masked: ${AUTH_TOKEN}"
  build:
    runs-on: ubuntu-latest
    needs: getauthtoken
    steps:
      - name: ConfirmOK
        env:
          AUTH_TOKEN: ${{needs.getauthtoken.outputs.auth_token}}
        run: |
          echo "Came through: ${AUTH_TOKEN}"
